#!/bin/bash

rm -f ./constant/cyclotron.stl
rm -f ./constant/cyclotron.fms
rm -rf ./constant/temp
rm -rf ./constant/polyMesh
rm -rf ./cases/dee
rm -rf ./cases/filament
rm -rf ./cases/filament2
rm -rf ./cases/faraday
rm -rf ./particleSim/0
